-- 코드를 작성해주세요

SELECT 
    T.ITEM_ID,
    T.ITEM_NAME,
    T.RARITY
FROM ITEM_INFO P
JOIN ITEM_TREE C ON P.ITEM_ID = C.PARENT_ITEM_ID
JOIN ITEM_INFO T ON C.ITEM_ID = T.ITEM_ID
WHERE P.RARITY = "RARE"
ORDER BY T.ITEM_ID DESC
